language: scala
scala:
   - 2.13.1
jdk:
  - openjdk11
stages:
  - test
  - name: deploy
    if: branch = master AND type = push AND fork = false
jobs:
  include:
    - stage: test
      script: ./build.sh
    - stage: deploy
    - script: >-
        "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin &&
        sbt clean compile docker:publish